### ISSUE TITLE
Game crashed when concrete powder was kept in water (very dangerous bug)

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/btwDecoAddon2#77] opened 2023-05-21 07:48 UTC
In order to turn the concrete powder into concrete, I put it in water and collected it. However, that would take a long time, so I tried to put concrete powder on top of concrete powder and collect the worst concrete, but the game crashed at that moment.
As soon as I tried to restart the game, the game crashed again and I couldn't open the data again.

It can be restarted if there is one powder and one block, but if multiple are installed, it seems impossible to restart.

I've investigated further, but the game crashes when I let the powder trickle down.

**Comment by ammoore00** [comment] 2023-07-25 05:04
Unable to reproduce. I'll be honest I only kind of understand what you're trying to say. I tried stacking a bunch of concrete powder above water and breaking the bottom-most block, but everything functions as expected.

Also, please always post a crash report when posting a crash bug. Doesn't really help me if you don't.

**Comment by ammoore00** [comment] 2023-09-09 03:42
Closing issue for now, unless I get more information

**Closed as completed by ammoore00** 2023-09-09 03:42 UTC
